//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookWay.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBKITAPYOLUEntities : DbContext
    {
        public DBKITAPYOLUEntities()
            : base("name=DBKITAPYOLUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UyeKayit> UyeKayit { get; set; }
        public virtual DbSet<Yorum> Yorum { get; set; }
        public virtual DbSet<PERSONEL> PERSONEL { get; set; }
    }
}
